execute if score __gen__ __bd__ matches 0 run return run scoreboard players set __cst__ __bd__ 0
execute if score __gen__ __bd__ matches 1000000000.. run return run scoreboard players set __cst__ __bd__ 10
execute if score __gen__ __bd__ matches ..-1000000000 run return run scoreboard players set __cst__ __bd__ 10
execute if score __gen__ __bd__ matches 100000000.. run return run scoreboard players set __cst__ __bd__ 9
execute if score __gen__ __bd__ matches ..-100000000 run return run scoreboard players set __cst__ __bd__ 9
execute if score __gen__ __bd__ matches 10000000.. run return run scoreboard players set __cst__ __bd__ 8
execute if score __gen__ __bd__ matches ..-10000000 run return run scoreboard players set __cst__ __bd__ 8
execute if score __gen__ __bd__ matches 1000000.. run return run scoreboard players set __cst__ __bd__ 7
execute if score __gen__ __bd__ matches ..-1000000 run return run scoreboard players set __cst__ __bd__ 7
execute if score __gen__ __bd__ matches 100000.. run return run scoreboard players set __cst__ __bd__ 6
execute if score __gen__ __bd__ matches ..-100000 run return run scoreboard players set __cst__ __bd__ 6
execute if score __gen__ __bd__ matches 10000.. run return run scoreboard players set __cst__ __bd__ 5
execute if score __gen__ __bd__ matches ..-10000 run return run scoreboard players set __cst__ __bd__ 5
execute if score __gen__ __bd__ matches 1000.. run return run scoreboard players set __cst__ __bd__ 4
execute if score __gen__ __bd__ matches ..-1000 run return run scoreboard players set __cst__ __bd__ 4
execute if score __gen__ __bd__ matches 100.. run return run scoreboard players set __cst__ __bd__ 3
execute if score __gen__ __bd__ matches ..-100 run return run scoreboard players set __cst__ __bd__ 3
execute if score __gen__ __bd__ matches 10.. run return run scoreboard players set __cst__ __bd__ 2
execute if score __gen__ __bd__ matches ..-10 run return run scoreboard players set __cst__ __bd__ 2
execute if score __gen__ __bd__ matches 1.. run return run scoreboard players set __cst__ __bd__ 1
execute if score __gen__ __bd__ matches ..-1 run return run scoreboard players set __cst__ __bd__ 1